export const PERMISSIONS = [
  { key: "leads:read", name: "View Leads", module: "leads" },
  { key: "leads:write", name: "Create/Edit Leads", module: "leads" },
  { key: "leads:delete", name: "Delete Leads", module: "leads" },
  { key: "leads:export", name: "Export Leads", module: "leads" },
  { key: "leads:import", name: "Import Leads", module: "leads" },
  { key: "customers:read", name: "View Customers", module: "customers" },
  { key: "customers:write", name: "Create/Edit Customers", module: "customers" },
  { key: "customers:delete", name: "Delete Customers", module: "customers" },
  { key: "customers:export", name: "Export Customers", module: "customers" },
  { key: "customers:import", name: "Import Customers", module: "customers" },
  { key: "contacts:read", name: "View Contacts", module: "contacts" },
  { key: "contacts:write", name: "Create/Edit Contacts", module: "contacts" },
  { key: "contacts:delete", name: "Delete Contacts", module: "contacts" },
  { key: "contacts:export", name: "Export Contacts", module: "contacts" },
  { key: "contacts:import", name: "Import Contacts", module: "contacts" },
  { key: "deals:read", name: "View Deals", module: "deals" },
  { key: "deals:write", name: "Create/Edit Deals", module: "deals" },
  { key: "deals:delete", name: "Delete Deals", module: "deals" },
  { key: "tasks:read", name: "View Tasks", module: "tasks" },
  { key: "tasks:write", name: "Create/Edit Tasks", module: "tasks" },
  { key: "tasks:delete", name: "Delete Tasks", module: "tasks" },
  { key: "quotes:read", name: "View Quotations", module: "quotes" },
  { key: "quotes:write", name: "Create/Edit Quotations", module: "quotes" },
  { key: "quotes:approve", name: "Approve Quotations", module: "quotes" },
  { key: "products:read", name: "View Products", module: "products" },
  { key: "products:write", name: "Create/Edit Products", module: "products" },
  { key: "invoices:read", name: "View Invoices", module: "invoices" },
  { key: "invoices:write", name: "Create/Edit Invoices", module: "invoices" },
  { key: "tickets:read", name: "View Tickets", module: "tickets" },
  { key: "tickets:write", name: "Create/Edit Tickets", module: "tickets" },
  { key: "campaigns:read", name: "View Campaigns", module: "campaigns" },
  { key: "campaigns:write", name: "Create/Edit Campaigns", module: "campaigns" },
  { key: "employees:read", name: "View Employees", module: "employees" },
  { key: "employees:write", name: "Manage Employees", module: "employees" },
  { key: "reports:read", name: "View Reports", module: "reports" },
  { key: "reports:export", name: "Export Reports", module: "reports" },
  { key: "settings:read", name: "View Settings", module: "settings" },
  { key: "settings:write", name: "Edit Settings", module: "settings" },
  { key: "audit:read", name: "View Audit Logs", module: "audit" },
  { key: "users:manage", name: "Manage Users", module: "users" },
  { key: "documents:read", name: "View Documents", module: "documents" },
  { key: "documents:write", name: "Upload Documents", module: "documents" },
] as const;

export type PermissionKey = (typeof PERMISSIONS)[number]["key"];

export const ALL_PERMISSION_KEYS = PERMISSIONS.map((p) => p.key);

export const ROLE_PERMISSION_MAP: Record<string, PermissionKey[] | "*"> = {
  SUPER_ADMIN: "*",
  ADMIN: "*",
  SALES_MANAGER: [
    "leads:read",
    "leads:write",
    "leads:delete",
    "leads:export",
    "leads:import",
    "customers:read",
    "customers:write",
    "customers:export",
    "customers:import",
    "contacts:read",
    "contacts:write",
    "contacts:export",
    "contacts:import",
    "deals:read",
    "deals:write",
    "deals:delete",
    "tasks:read",
    "tasks:write",
    "quotes:read",
    "quotes:write",
    "quotes:approve",
    "products:read",
    "invoices:read",
    "reports:read",
    "reports:export",
    "employees:read",
    "documents:read",
    "documents:write",
  ],
  SALES_EXECUTIVE: [
    "leads:read",
    "leads:write",
    "leads:export",
    "customers:read",
    "customers:write",
    "customers:export",
    "customers:import",
    "contacts:read",
    "contacts:write",
    "contacts:export",
    "contacts:import",
    "deals:read",
    "deals:write",
    "tasks:read",
    "tasks:write",
    "quotes:read",
    "quotes:write",
    "products:read",
    "documents:read",
    "documents:write",
  ],
  MARKETING: [
    "leads:read",
    "leads:write",
    "leads:import",
    "campaigns:read",
    "campaigns:write",
    "contacts:read",
    "contacts:export",
    "contacts:import",
    "reports:read",
    "documents:read",
  ],
  SUPPORT: [
    "customers:read",
    "customers:export",
    "contacts:read",
    "contacts:export",
    "tickets:read",
    "tickets:write",
    "tasks:read",
    "tasks:write",
    "documents:read",
    "documents:write",
  ],
  ACCOUNTANT: [
    "customers:read",
    "customers:export",
    "invoices:read",
    "invoices:write",
    "quotes:read",
    "products:read",
    "reports:read",
    "reports:export",
    "documents:read",
  ],
  VIEWER: [
    "leads:read",
    "customers:read",
    "customers:export",
    "contacts:read",
    "contacts:export",
    "deals:read",
    "tasks:read",
    "quotes:read",
    "products:read",
    "invoices:read",
    "tickets:read",
    "campaigns:read",
    "employees:read",
    "reports:read",
    "documents:read",
  ],
};

export function hasPermission(
  userPermissions: string[] | undefined,
  required: PermissionKey | PermissionKey[],
) {
  if (!userPermissions?.length) return false;
  if (userPermissions.includes("*")) return true;
  const needed = Array.isArray(required) ? required : [required];
  return needed.every((p) => userPermissions.includes(p));
}
